[package]
name = "badger-transport"
version = "0.1.0"
edition = "2021"

[dependencies]
badger-core = { path = "../badger-core" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }